name: Build and Push Docker Image

on:
  push:
    paths-ignore:
      - "README.md"
      - "LICENSE"
      - "docker-compose.yml"
      - "docker-compose.example.yml"
      - "mode_list.json"
    branches:
      - master
  pull_request:
    paths-ignore:
      - "README.md"
      - "LICENSE"
      - "docker-compose.yml"
      - "docker-compose.example.yml"
      - "mode_list.json"
    branches:
      - master

env:
  IMAGE_NAME_DOCKERHUB: nerdneils/openapi-model-replace

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Check Out Code
        uses: actions/checkout@v4

      - name: Set Up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          username: nerdneils
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and Push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: docker.io/nerdneils/${{ env.IMAGE_NAME_DOCKERHUB }}:latest
